{
	"version": 1495634266,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/bulletmc-sheet0.png",
		"images/wing-sheet0.png",
		"images/enemy-sheet0.png",
		"images/enemy-sheet1.png",
		"images/hpbar-sheet0.png",
		"images/hpbar-sheet1.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/tiledbackground.png",
		"images/boom-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite5-sheet1.png",
		"images/sprite5-sheet2.png",
		"images/sprite6-sheet0.png",
		"images/sprite6-sheet1.png",
		"images/sprite6-sheet2.png",
		"images/sprite3-sheet0.png",
		"images/boom2-sheet0.png",
		"images/boom2-sheet1.png",
		"images/boom2-sheet2.png",
		"images/sprite7-sheet0.png",
		"images/sprite7-sheet1.png",
		"images/sprite7-sheet2.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/spritefont.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"media/lazer fire 1.m4a",
		"media/lazer fire 1.ogg",
		"media/pickup_coins04.m4a",
		"media/pickup_coins04.ogg",
		"media/bom17_a.m4a",
		"media/bom17_a.ogg",
		"media/epicarpg.m4a",
		"media/epicarpg.ogg",
		"media/explosion 2.m4a",
		"media/explosion 2.ogg",
		"media/explosion 3.m4a",
		"media/explosion 3.ogg",
		"media/pickup_specialfilm03.m4a",
		"media/pickup_specialfilm03.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}